import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'error-container': '#ffdad6',
        'on-secondary-fixed-variant': '#733500',
        'surface-dim': '#dadad8',
        'surface-tint': '#3b5ca3',
        'on-primary': '#ffffff',
        'primary-fixed-dim': '#b0c6ff',
        'surface-container-lowest': '#ffffff',
        primary: '#001f50',
        surface: '#f9f9f7',
        'on-primary-fixed': '#001945',
        'outline-variant': '#c4c6d2',
        'secondary-fixed-dim': '#ffb689',
        'on-tertiary-container': '#94a0b8',
        'tertiary-container': '#2b374b',
        error: '#ba1a1a',
        'secondary-container': '#fe8015',
        'on-surface': '#1a1c1b',
        'on-primary-fixed-variant': '#204489',
        'tertiary-fixed-dim': '#bbc7e0',
        'surface-variant': '#e2e3e1',
        outline: '#747782',
        'on-background': '#1a1c1b',
        'inverse-surface': '#2f3130',
        'primary-container': '#063378',
        'tertiary-fixed': '#d7e3fd',
        'on-surface-variant': '#434651',
        'inverse-on-surface': '#f1f1ef',
        'on-tertiary': '#ffffff',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#101c2f',
        'on-secondary': '#ffffff',
        'surface-container-highest': '#e2e3e1',
        'on-tertiary-fixed-variant': '#3b475c',
        'surface-container-high': '#e8e8e6',
        'on-secondary-container': '#5f2b00',
        'inverse-primary': '#b0c6ff',
        'on-primary-container': '#7f9ee9',
        'on-error-container': '#93000a',
        'on-secondary-fixed': '#311300',
        background: '#f9f9f7',
        'primary-fixed': '#d9e2ff',
        'surface-bright': '#f9f9f7',
        secondary: '#974800',
        'surface-container': '#eeeeec',
        'secondary-fixed': '#ffdbc7',
        tertiary: '#162235',
        'surface-container-low': '#f4f4f2',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        lg: '24px',
        gutter: '24px',
        unit: '8px',
        xl: '40px',
        md: '16px',
        sm: '8px',
        xxl: '64px',
        xs: '4px',
        'container-max': '1200px',
      },
      fontFamily: {
        h1: ['var(--font-sora)', 'system-ui', 'sans-serif'],
        'h1-mobile': ['var(--font-sora)', 'system-ui', 'sans-serif'],
        h2: ['var(--font-sora)', 'system-ui', 'sans-serif'],
        'h2-mobile': ['var(--font-sora)', 'system-ui', 'sans-serif'],
        h3: ['var(--font-sora)', 'system-ui', 'sans-serif'],
        'body-md': ['var(--font-inter)', 'system-ui', 'sans-serif'],
        'body-lg': ['var(--font-inter)', 'system-ui', 'sans-serif'],
        'label-bold': ['var(--font-inter)', 'system-ui', 'sans-serif'],
        caption: ['var(--font-inter)', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        h1: ['40px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h1-mobile': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        h3: ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'h2-mobile': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        h2: ['32px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-bold': ['14px', { lineHeight: '1.4', fontWeight: '600' }],
        caption: ['12px', { lineHeight: '1.4', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1200px',
      },
    },
  },
  plugins: [],
}

export default config
